### PR TITLE
feat: godot 4.x support

### PR DESCRIPTION
**Pull request by tripodsan**
- migrating to godot 4.x
- suppress update in `_process` when not modified
- send `change` event when modified
- add debug labels for `theta` and `phi`

### CODE REVIEW

**Comment by tripodsan** [comment]
@LucaJunge I like your plugin and want to use it in godot 4.x

If you are interested, either create a 4.x branch and I rebase my PR or create a 3.x maintenance branch....

**Comment by LucaJunge** [comment]
@tripodsan Thanks for migrating it to 4.0!

I think it would be best to use main as the branch for 4.x and create a separate 3.x branch for the original plugin. I will take a look at the PR later today and set everything up.

**Comment by LucaJunge** [comment]
Your edits unfortunately converted the tabs to spaces, could you fix that, before I merge?

**Comment by tripodsan** [comment]
> Your edits unfortunately converted the tabs to spaces, could you fix that, before I merge?

do you really like having tabs? using spaces lead to better ineropability with external editors... but of course I can revert it.

**Comment by tripodsan** [comment]
ok. I change it to tabs.

**Pull request merged**
